### PR TITLE
Fixes #725 - allow live views to be rendered inside live components

### LINKED ISSUE #725: LiveView -> LiveComponent -> LiveView nesting throws an exception
### Environment

* Elixir version (elixir -v): 1.9.2
* Phoenix version (mix deps): 1.5.0-dev (afeffe8)
* Phoenix LiveView version (mix deps): 0.10.0 (fa668d1)

### Actual behavior

I have a top level `LiveView`, using the `live` router macro.  This contains a `LiveComponent`, which in turn contains another `LiveView`.

In this situation I get the following error:

```
** (exit) an exception was raised:
    ** (KeyError) key :conn_session not found in: %{}
        (phoenix_live_view) lib/phoenix_live_view/static.ex:228: Phoenix.LiveView.Static.disconnected_nested_render/6
        (alchemy_web) lib/alchemy_web/templates/manageable/selector.html.leex:37: anonymous fn/2 in AlchemyWeb.ManageableView."selector.html"/1
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:221: Phoenix.LiveView.Diff.traverse/5
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:452: Phoenix.LiveView.Diff.render_component/7
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:401: anonymous fn/5 in Phoenix.LiveView.Diff.render_pending_components/5
        (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
        (stdlib) maps.erl:232: :maps.fold_1/3
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:384: Phoenix.LiveView.Diff.render_pending_components/5
        (phoenix_live_view) lib/phoenix_live_view/diff.ex:95: Phoenix.LiveView.Diff.render/3
        (phoenix_live_view) lib/phoenix_live_view/static.ex:275: Phoenix.LiveView.Static.to_rendered_content_tag/4
        (phoenix_live_view) lib/phoenix_live_view/static.ex:137: Phoenix.LiveView.Static.render/3
        (phoenix_live_view) lib/phoenix_live_view/controller.ex:35: Phoenix.LiveView.Controller.live_render/3
        (phoenix) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (alchemy_web) lib/alchemy_web/endpoint.ex:1: AlchemyWeb.Endpoint.plug_builder_call/2
        (alchemy_web) lib/plug/debugger.ex:132: AlchemyWeb.Endpoint."call (overridable 3)"/2
        (alchemy_web) lib/alchemy_web/endpoint.ex:1: AlchemyWeb.Endpoint.call/2
        (phoenix) lib/phoenix/endpoint/cowboy2_handler.ex:42: Phoenix.Endpoint.Cowboy2Handler.init/4
        (cowboy) /Users/dave/Projects/Couloir/ctp/alchemy/deps/cowboy/src/cowboy_handler.erl:41: :cowboy_handler.execute/2
        (cowboy) /Users/dave/Projects/Couloir/ctp/alchemy/deps/cowboy/src/cowboy_stream_h.erl:320: :cowboy_stream_h.execute/3
        (cowboy) /Users/dave/Projects/Couloir/ctp/alchemy/deps/cowboy/src/cowboy_stream_h.erl:302: :cowboy_stream_h.request_process/3
```

### PR DESCRIPTION
**Pull request by ccapndave**
See #725 for details

### CODE REVIEW

File: lib/phoenix_live_view/diff.ex [hunk 1]
```diff
@@ -356,7 +356,7 @@ defmodule Phoenix.LiveView.Diff do
     %{
       socket
       | assigns: assigns,
-        private: private,
+        private: private |> Enum.into(Map.take(socket.private, [:conn_session])),
```
Comment (josevalim) [inline lib/phoenix_live_view/diff.ex]: We only need to do this on line #349. You can make the third argument be `Map.take(socket.private, [:conn_session])`. Can you please give it a try?

File: test/support/live_views/live_in_component.ex [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+
+defmodule Phoenix.LiveViewTest.NestedComponent do
+  use Phoenix.LiveComponent
+
+  def render(assigns) do
+    ~L"<%= live_render @socket, Phoenix.LiveViewTest.NestedLive2, id: :nested_live_2 %>"
+  end
+end
+
+defmodule Phoenix.LiveViewTest.NestedLive2 do
```
Comment (josevalim) [inline test/support/live_views/live_in_component.ex]:
```suggestion
defmodule Phoenix.LiveViewTest.LiveInComponent do
```

**Comment by ccapndave** [comment]
Sounds good - changes made and pushed.
