### PR TITLE
Do not crash on components without html tags

### LINKED ISSUE #985: Components that render an empty ~L causes issues
That's because the component exists but there is no `data-phx-component` on the page. We should probably warn for those cases in the same way we warn for only text components. This is also something we can check on the server too.

### PR DESCRIPTION
**Pull request by josevalim**
Instead we create a span, similar to what we do for text nodes.

Closes #985.

### CODE REVIEW

File: assets/test/view_test.js [hunk 1]
```diff
@@ -264,6 +264,67 @@ describe("View + DOM", function() {
     expect(form.querySelector("button").dataset.phxDisabled).toBeTruthy()
     expect(form.querySelector("input").dataset.phxReadonly).toBeTruthy()
   })
+
+  test("empty diff undoes refs and pending attributes", () => {
```
Comment (josevalim) [inline assets/test/view_test.js:268]: This test was already written. I just moved it back because it was in the wrong group.
