### PR TITLE
Use Phoenix.LiveView layout opt for static render

### LINKED ISSUE #2397: Layouts with `use Phoenix.LiveView` don't work on disconnected render
### Environment

* Elixir version (elixir -v): Elixir 1.14.3 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): 1.7.0-rc.2
* Phoenix LiveView version (mix deps): 0.18.7
* Operating system: Pop!_OS 22.04 LTS
* Browsers you attempted to reproduce this bug on (the more the merrier): Firefox, Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

When using the `:layout` option of `use Phoenix.LiveView` to specify a layout, the layout is not included in the disconnected render.  Only the root layout and the live view itself are rendered.

This seems related to #2376, and was possibly introduced by #2387.  The behavior is consistent with [setting the layout to false](https://github.com/phoenixframework/phoenix_live_view/pull/2387/files#diff-d6e0926af881a2fd38a6f7992ed706c597be93ae542f4149e71f9442887be1ecR70).

### Expected behavior

When specifying a layout with the `:layout` option of `use Phoenix.LiveView`, the layout should be used for the disconnected render.

### PR DESCRIPTION
**Pull request by jdav-dev**
Fixes  #2397.

### CODE REVIEW

File: lib/phoenix_live_view/static.ex [hunk 1]
```diff
@@ -109,9 +108,9 @@ defmodule Phoenix.LiveView.Static do
           conn_session: conn_session,
           lifecycle: lifecycle,
           root_view: view,
-          live_layout: live_layout,
           __changed__: %{}
-        },
+        }
+        |> maybe_get_live_layout(live_session),
```
Comment (josevalim) [inline lib/phoenix_live_view/static.ex:113]:
```suggestion
        |> maybe_put_live_layout(live_session),
```

File: lib/phoenix_live_view/static.ex [hunk 2]
```diff
@@ -62,12 +62,12 @@ defmodule Phoenix.LiveView.Static do
     _ -> %{}
   end
 
-  defp maybe_get_live_layout(%{extra: %{layout: layout}}) do
-    layout
+  defp maybe_get_live_layout(private, %{extra: %{layout: layout}}) do
```
Comment (josevalim) [inline lib/phoenix_live_view/static.ex:65]:
```suggestion
  defp maybe_put_live_layout(private, %{extra: %{layout: layout}}) do
```

File: lib/phoenix_live_view/static.ex [hunk 3]
```diff
@@ -62,12 +62,12 @@ defmodule Phoenix.LiveView.Static do
...
+    Map.put(private, :live_layout, layout)
   end
 
-  defp maybe_get_live_layout(_) do
-    false
+  defp maybe_get_live_layout(private, _live_session) do
```
Comment (josevalim) [inline lib/phoenix_live_view/static.ex:69]:
```suggestion
  defp maybe_put_live_layout(private, _live_session) do
```

File: test/phoenix_live_view/integrations/layout_test.exs [hunk 4]
```diff
@@ -34,6 +34,13 @@ defmodule Phoenix.LiveView.LayoutTest do
              "LIVELAYOUTSTART-246-The value is: 246-LIVELAYOUTEND\n"
   end
 
+  test "is picked from config on first render", %{conn: conn} do
```
Comment (josevalim) [inline test/phoenix_live_view/integrations/layout_test.exs:37]:
```suggestion
  test "is picked from use on first render", %{conn: conn} do
```

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
