### PR TITLE
Fix open_browser not working on WSL for project under unix FS

### LINKED ISSUE #3063: open_browser not working on WSL2 Ubuntu-20.04
### Environment

* Elixir version (elixir -v): Elixir 1.14.0 (compiled with Erlang/OTP 25)
* Phoenix version (mix deps): phoenix 1.7.10
* Phoenix LiveView version (mix deps): phoenix_live_view 0.20.2
* Operating system: WSL2 Ubuntu-20.04
* Browsers you attempted to reproduce this bug on (the more the merrier): firefox installed in WSL2 Ubuntu-20.04
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

```
  test "test open_browser", %{conn: conn} do
    {:ok, live, _html} = live(conn, ~p"/")
    
    live
    |> open_browser()
  end
```

Running the above test, `open_browser` fails with an error 

```
'\\wsl.localhost\Ubuntu-20.04\home\<username>\workspace\phoenix_live_view'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
Invalid switch - "/tmp".
```

### Expected behavior

Should open the firefox installed in WSL2 Ubuntu-20.04

### PR DESCRIPTION
**Pull request by waranlogesh**
- Fixes #3063
- I am not sure why `cmd.exe` check was done for `unix` condition (could find it was added here https://github.com/phoenixframework/phoenix_live_view/commit/a6494c579d4750da9b437f35907d7e87aa5cf579 by @josevalim). But even if it is for the WSL case, it is not working. I think the better way is to treat WSL as another variant of Linux and use the same flow.

### CODE REVIEW

**Comment by josevalim** [comment]
We added that for WSL1 :( Ideally we would find a way to make the cmd version work on both systems.

**Comment by waranlogesh** [comment]
@josevalim I tried to run the cmd in WSL 1 but it failed there too.
image
image

The real issue is `cmd.exe` worked only for WSL with the project under Windows path (c:\ or other drives) so it is not due to WSL 1 and 2 incompatibility.

Since my project is inside WSL using unix path(/home/logesh/), `cmd.exe` fails and there [isn't a clean way](https://stackoverflow.com/questions/23673632/cmd-exe-was-started-with-the-above-path-as-the-current-directory-unc-paths-are) to make cmd.exe work with unix path.  So I added a regex to detect windows path and use `cmd.exe` if not `xdg-open`

File: lib/phoenix_live_view/test/live_view_test.ex [hunk 1]
```diff
@@ -1574,7 +1574,13 @@ defmodule Phoenix.LiveViewTest do
 
         {:unix, _} ->
           if System.find_executable("cmd.exe") do
-            {"cmd.exe", ["/c", "start", path]}
+            win_path_regex = ~r/^([^\\]+\\)*?$/
```
Comment (josevalim) [inline lib/phoenix_live_view/test/live_view_test.ex:1577]: Could we check instead if the path has a `\\`? Or is it important to check that it does not start with a `\\`?
