### PR TITLE
Fix stream reset when patching

### LINKED ISSUE #2629: Stream is not reset in handle_params on patch
### Environment

* Elixir version (elixir -v): 1.14.4
* Phoenix version (mix deps): main
* Phoenix LiveView version (mix deps): main
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier): n/a
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: n/a

### Actual behavior

Using `stream(.., reset: true)` in handle_params when using `patch` does not reset the stream.

### Expected behavior

The stream should be reset.

I have added a test to demonstrate this: https://github.com/phoenixframework/phoenix_live_view/compare/main...nmk:phoenix_live_view:stream-reset-on-patch

Is this a problem with the test or my usage of `stream(..., reset: true)`?

### PR DESCRIPTION
**Pull request by nmk**
Fixes #2629

### CODE REVIEW

File: lib/phoenix_live_view/test/dom.ex [hunk 1]
```diff
@@ -451,7 +451,7 @@ defmodule Phoenix.LiveViewTest.DOM do
                 if deleted? do
                   acc |> List.delete_at(old_index) |> List.insert_at(insert_at, child)
                 else
-                  acc
+                  acc |> List.replace_at(old_index, child)
```
Comment (chrismccord) [inline lib/phoenix_live_view/test/dom.ex:454]:
```suggestion
                  List.replace_at(acc, old_index, child)
```

**Comment by chrismccord** [comment]
Thank you so much!! ❤️❤️❤️🐥🔥
