### PR TITLE
Handle class option for container given as a list on live redirect (#2417)

### LINKED ISSUE #2417: LiveView container option doesn't handle lists of classes
When using the `container:` option when `use`ing liveview, we mistakenly used a list for multiple class names, like so:

```elixir
use Phoenix.LiveView,
  layout: {MyAppWeb.Layouts, :app},
  container: {:div, class: ~w(h-full overflow-hidden print:overflow-visible)}
```

The docs show it as a string but does not explicitly state it has to be. Since heex accept lists of classes for tags, we mistakenly used a list instead of a string and saw odd results.

### Environment

* Elixir version (elixir -v): `Elixir 1.14.0 (compiled with Erlang/OTP 25)`
* Phoenix version (mix deps): `phoenix 1.7.0-rc.2`
* Phoenix LiveView version (mix deps): `phoenix_live_view 0.18.11`
* Operating system: mac os 12.2.1
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: N/A

### Actual behavior

When the dom is updated via a `push_navigate`, the classes were joined with a comma on the live view container. E.g.: `h-full,overflow-hidden,print:overflow-visible`

### Expected behavior

The classes should be rendered with spaces, e.g.: `"h-full overflow-hidden print:overflow-visible"`

Or, the docs should be updated to explicitly state a string is required.

### PR DESCRIPTION
**Pull request by begedin**
# What this does

It attempts to fix #2417 

In tests, the DOM module relies on Floki to produce html, and Floki will take an attribute given as a list and combine it into a single string using `Enum.join("")`. This makes change in `DOM.replace_root_container/3` which converts the class attribute specifically, when given as list, into a binary using `Enum.join(" ")`.

This aligns tests with the next change, that is the actual "fix"

In actual code, when a container is given a list of classes instead of a single string, this works just fine on view first render, but on `live_redirect` it will also do a join using `""`.

So the same change for the class attribute as in the `DOM` module is made in `Channel.put_container/3`

# Is this the way to go?

@josevalim very clearly instructed we should just verify whether the class attribute is a binary or not and keep it at that, but the thing is, I went with the intend on looking into it and gave it a try, but then realised class as a list actually does work on initial view render, it's only on `live_redirect` that it fails.

So I opted for this to just start a conversation and I'm happy to close it without any changes pushed upstream.

I'm also 100% sure the tests I have are disorganised so I'm open to pointers on which to keep, how to name them and where to put them.

### CODE REVIEW

File: lib/phoenix_live_view/test/dom.ex [hunk 1]
```diff
@@ -328,6 +328,9 @@ defmodule Phoenix.LiveViewTest.DOM do
       |> Enum.map(fn {attr, value} -> {String.downcase(to_string(attr)), value} end)
       |> Enum.filter(fn {attr, _value} -> attr not in reserved_attrs end)
       |> Enum.reduce(container_attrs_list, fn {attr, new_val}, acc ->
+        new_val =
+          if attr == "class" and is_list(new_val), do: Enum.join(new_val, " "), else: new_val
```
Comment (josevalim) [inline lib/phoenix_live_view/test/dom.ex:332]: Thanks for the PR! I think it would be best to guarantee the server always sends it as a string, so we don't need this logic here. Do we have a similar logic in .js too?

Comment (begedin) [reply lib/phoenix_live_view/test/dom.ex:332]: I was thinking the same.

As far as I can tell, and it's been a while since I did the debugging, the frontend logic is in `dom.js` `replaceRootContainer` which only blindly maps over the attributes and doesn't check value.

So yes, that would be an argument in favor of removing the change from `dom.ex`. Is that what you mean? That would mean basically reverting one of the two commits here.

Comment (begedin) [reply lib/phoenix_live_view/test/dom.ex:332]: I will do a quick check and come back here

Comment (josevalim) [reply lib/phoenix_live_view/test/dom.ex:332]: Yes, reverting the dom.ex change. And making sure that we don't pass a list anywhere else :)

Comment (begedin) [reply lib/phoenix_live_view/test/dom.ex]: We retrieve the container using `Route.container/1` and this function is only ever called from this one location.

```elixir
# Route.container/1

def container(%Route{} = route) do
  route.opts[:container] || route.view.__live__()[:container]
end
```

Any other reference to container is in 

- `__before_compile__` of `Phoenix.Component` where we pass it forward with a default ✅ safe

```elixir
    container = opts[:container] || {:div, []}

    live = %{
      container: container,
      name: name,
      kind: :view,
      module: env.module,
      layout: layout,
      lifecycle: lifecycle,
      log: log
    }
```

- `Router.validate_live_opts!` where we just validate opts are a list ✅ safe

```Elixir
Enum.each(opts, fn
  {:container, {tag, attrs}} when is_atom(tag) and is_list(attrs) ->
    :ok

{:container, val} ->
  raise ArgumentError, """
  expected live :container to be a tuple matching {atom, attrs :: list}, got: #{inspect(val)}
  """
```

- `Static.container` (private) where we just merge some options

This is used in `render` and `nested_render` which would I assume do the initial rendering server-side using Phoenix.HTML? I also assume that then handles a class given as a list internally, since that was, I think, my experience with classic phoenix. So i'm gonna go with ☑️ sefe-ish?

```Elixir
defp container(%{container: {tag, attrs}}, opts) do
  case opts[:container] do
    {tag, extra} -> {tag, Keyword.merge(attrs, extra)}
    nil -> {tag, attrs}
  end
end
```

**Comment by begedin** [comment]
Did the revert, as agreed. Should I rebase interactively to drop the two opposite logs, so just the one commit is left? 

I'm not sure if a squash is being done at merge or not.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
