### PR TITLE
Fixing where push_redirect will cause a non-main liveview to buf…

### LINKED ISSUE #2057: Liveview (still) won't re-render if pubsub message received when livepatch/live redirect
### Environment

* Elixir version (elixir -v): Erlang/OTP 25 [erts-13.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns] [dtrace] Elixir 1.13.4 (compiled with Erlang/OTP 24) **and** Erlang/OTP 24 [erts-12.3.1] [source] [64-bit] [smp:16:6] [ds:16:6:10] [async-threads:1] [jit] Elixir 1.13.0 (compiled with Erlang/OTP 24)

* Phoenix version (mix deps): phoenix 1.6.10 (Hex package) (mix)  locked at 1.6.10 (phoenix) 08cf70d4
* Phoenix LiveView version (mix deps): phoenix_live_view 0.17.10 (Hex package) (mix)  locked at 0.17.10 (phoenix_live_view) 3e77cf0f
* Operating system: Ubuntu 20.04.2 LTS and OSX Monterey 12.4
* Browsers you attempted to reproduce this bug on (the more the merrier): Brave, Firefox, Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Same issue as here: https://github.com/phoenixframework/phoenix_live_view/issues/1867. The views assigns do reflect the updated values, and the changes are retained between repeated updates, but the view is never re-rendered. 

There was fix https://github.com/phoenixframework/phoenix_live_view/commit/f42d3ff465f13dcf8cf3cea04b2011f1a46f9c17 to fix this issue but it seems to still be an issue. 

The liveview isn't updated but if inspecting the assigns the messages are received and stored. It works if a delay is added either between pubsub message sent and redirect or after redirect and message received (but of course that is a terrible solution to intentionally delay the app for the user). 

See my bug replication: https://github.com/victorbjorklund/notifyapp-bug-example 

(if using gitpod the repo contains the correct set up so this will launch the project https://gitpod.io/#https://github.com/victorbjorklund/notifyapp-bug-example). You can click add a new note with or without a delay to see the difference. 

### Expected behavior

Liveview should re-render when the assigns are updated.

### PR DESCRIPTION
**Pull request by jeregrine**
Closes #2057

### CODE REVIEW

File: assets/js/phoenix_live_view/view.js [hunk 1]
```diff
@@ -470,7 +470,7 @@ export default class View {
   }
 
   update(diff, events){
-    if(this.isJoinPending() || (this.liveSocket.hasPendingLink() && !DOM.isPhxSticky(this.el))){
+    if(this.isJoinPending() || (this.liveSocket.hasPendingLink() && this.root.isMain() && !DOM.isPhxSticky(this.el))){
```
Comment (chrismccord) [inline assets/js/phoenix_live_view/view.js:473]:
```suggestion
    if(this.isJoinPending() || (this.liveSocket.hasPendingLink() && this.root.isMain())){
```

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥
