### PR TITLE
Fix @doc generation for :global attribute type (fixes #2709)

### LINKED ISSUE #2709: Doc string for global attributes not rendered in documentation
### Environment

* Elixir version (elixir -v): 1.12
* Phoenix version (mix deps): 1.7.6
* Phoenix LiveView version (mix deps): 0.19.3
* Operating system: Mac OS
* Browsers you attempted to reproduce this bug on (the more the merrier): 
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no:

### Actual behavior

Using `attr :rest, :global, doc: "Something"` doesn't fail to compile, but the documentation is not rendered by automatically appended chunk.

### Expected behavior

Documentation for global attributes is rendered as well. My usecase here is documented where the global attributes are set to.

### PR DESCRIPTION
**Pull request by begedin**
The codebase contains code that clearly shows there was intent to support both `doc` and `include` options for an attribute of type `:global`, but after adding some test coverage, it became evident it wasn't being reached.

After coverage was added and the bug was fixed, I took the liberty to refactor the code a bit.

Fixes #2709

### CODE REVIEW

File: lib/phoenix_component/declarative.ex [hunk 1]
```diff
@@ -817,21 +817,20 @@ defmodule Phoenix.Component.Declarative do
   defp build_attrs_docs(attrs) do
     [
       "## Attributes\n",
-      for attr <- attrs, attr.doc != false, attr.type != :global, into: [] do
```
Comment (begedin) [inline lib/phoenix_component/declarative.ex:820]: We were skipping proper generation for `:global` here...

File: lib/phoenix_component/declarative.ex [hunk 2]
```diff
@@ -817,21 +817,20 @@ defmodule Phoenix.Component.Declarative do
...
-          build_attr_name(attr),
-          build_attr_type(attr),
-          build_attr_required(attr),
-          build_hyphen(attr),
-          build_attr_doc_and_default(attr, "  "),
-          build_attr_values_or_examples(attr)
-        ]
-      end,
-      if Enum.any?(attrs, &(&1.type == :global)) do
-        "\n* Global attributes are accepted."
```
Comment (begedin) [inline lib/phoenix_component/declarative.ex:832]: And then adding a catch-all sentence at the end

File: lib/phoenix_component/declarative.ex [hunk 3]
```diff
@@ -904,17 +903,18 @@ defmodule Phoenix.Component.Declarative do
   end
 
   defp build_attr_doc_and_default(%{doc: doc, type: :global, opts: opts}, indent) do
```
Comment (begedin) [inline lib/phoenix_component/declarative.ex:905]: But, clearly, at some point, we intended to call this function for the global type.

File: lib/phoenix_component/declarative.ex [hunk 4]
```diff
@@ -817,21 +817,20 @@ defmodule Phoenix.Component.Declarative do
...
+        else
+          [
+            "\n* ",
+            build_attr_name(attr),
+            build_attr_type(attr),
+            build_attr_required(attr),
+            build_hyphen(attr),
+            build_attr_doc_and_default(attr, "  "),
+            build_attr_values_or_examples(attr)
+          ]
```
Comment (begedin) [inline lib/phoenix_component/declarative.ex:832]: The change is that we now call the function that is expecting to be called, but in the case of global, only that function. The `Global attributes are accepted` message has been moved into it to simplify.

File: lib/phoenix_component/declarative.ex [hunk 5]
```diff
@@ -904,17 +903,18 @@ defmodule Phoenix.Component.Declarative do
...
+    [
+      # always included
+      "\n* Global attributes are accepted.",
+      if(doc, do: [" ", build_doc(doc, indent, false)], else: []),
+      case Keyword.get(opts, :include) do
+        inc when is_list(inc) and inc != [] ->
+          [" ", "Supports all globals plus:", " ", build_literal(inc), "."]
+
+        _ ->
+          []
```
Comment (begedin) [inline lib/phoenix_component/declarative.ex:915]: We start off with the generic line, then maybe add docs, then maybe add includes.

File: test/phoenix_component/declarative_assigns_test.exs [hunk 6]
```diff
@@ -1020,7 +1035,7 @@ defmodule Phoenix.ComponentDeclarativeAssignsTest do
     assert Enum.find_value(abstract_code, fn
              {:function, line, :fun_doc_false, 1, _} -> line
              _ -> nil
-           end) == 105
+           end) == 114
```
Comment (begedin) [inline test/phoenix_component/declarative_assigns_test.exs:1038]: Lines shifted, so had to update this

File: lib/phoenix_component/declarative.ex (hunk 1 above)
Comment (josevalim) [reply lib/phoenix_component/declarative.ex:820]: I think it was written in this style so the `:global` attribute always comes last. Should we revert this particular change?

File: lib/phoenix_component/declarative.ex (hunk 5 above)
Comment (josevalim) [reply lib/phoenix_component/declarative.ex:914]: Perfect :heart:

File: lib/phoenix_component/declarative.ex (hunk 1 above)
Comment (begedin) [reply lib/phoenix_component/declarative.ex:820]: That does make sense. I'll revert that part, then and then we can follow up on performance not potentially being enough

Comment (begedin) [reply lib/phoenix_component/declarative.ex:820]: I skipped global in the first for pass, then did an enum find at the end for the global. This means that only one global actually gets docs generated. I'm not sure if multiple globals should be supported?

It also means potentially 2 passes through the attrs list so not as performant as it technically could be, but trying to do it all in one pass means a reduce or some other less clear alternative.

File: lib/phoenix_component/declarative.ex [hunk 7]
```diff
@@ -828,10 +828,10 @@ defmodule Phoenix.Component.Declarative do
...
       end,
-      if Enum.any?(attrs, &(&1.type == :global)) do
-        "\n* Global attributes are accepted."
-      else
-        ""
+      # global always goes at the end
+      case Enum.find(attrs, &(&1.type === :global)) do
+        nil -> []
+        attr -> build_attr_doc_and_default(attr, "  ")
       end
```
Comment (begedin) [inline lib/phoenix_component/declarative.ex:835]: Is the inline comment too much? I know code should be self-documenting, and a new test case ensures global goes last, so I can remove that part.

File: lib/phoenix_component/declarative.ex [hunk 8]
```diff
@@ -817,7 +817,7 @@ defmodule Phoenix.Component.Declarative do
   defp build_attrs_docs(attrs) do
     [
       "## Attributes\n",
-      for attr <- attrs, attr.doc != false, attr.type != :global, into: [] do
+      for attr <- attrs, attr.doc != false && attr.type != :global, into: [] do
```
Comment (josevalim) [inline lib/phoenix_component/declarative.ex:820]:
```suggestion
      for attr <- attrs, attr.doc != false and attr.type != :global do
```

File: lib/phoenix_component/declarative.ex [hunk 9]
```diff
@@ -817,7 +817,7 @@ defmodule Phoenix.Component.Declarative do
   defp build_attrs_docs(attrs) do
     [
       "## Attributes\n",
-      for attr <- attrs, attr.doc != false, attr.type != :global, into: [] do
+      for attr <- attrs, attr.doc != false and attr.type != :global do
```
Comment (begedin) [inline lib/phoenix_component/declarative.ex:820]: Hm, @josevalim i didn't realise I switched from a "multiple filters" approach in the comprehension and went with `and`. I see you switched it to `&&` but should it be reverted back to multiple filters?

Comment (josevalim) [reply lib/phoenix_component/declarative.ex:820]: It is all the same!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
