### PR TITLE
Relax regex used during js navigation (redirect)

### LINKED ISSUE #2334: Server Process crashes when using `JS.navigate("/")`
### Environment

* Elixir version (elixir -v):  1.14.1
* Phoenix version (mix deps):  1.6.15
* Phoenix LiveView version (mix deps):  0.18.3
* Operating system: N/A
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome Based
* Does the problem persist after removing "assets/node_modules" and trying again? yes

### Actual behavior

The liveview process crashes with this:
```
** (CaseClauseError) no case clause matching: %Phoenix.LiveView.Route{path: [], view: AppWeb.HomeLive.Index, action: :index, opts: [action: :index, router: AppWeb.Router], live_session: %{extra: %{on_mount: [%{function: &AppWeb.InitAssigns.on_mount/4, id: {AppWeb.InitAssigns, :default}, stage: :mount}], session: %{}}, name: :default, vsn: 1668894584134865752}, params: %{}, uri: %URI{scheme: nil, userinfo: nil, host: nil, port: nil, path: "/", query: nil, fragment: nil}}
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/channel.ex:990: Phoenix.LiveView.Channel.verified_mount/8
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/channel.ex:59: Phoenix.LiveView.Channel.handle_info/2
```
Which is because it expects `host` and `scheme` to be defined in the `uri`  - and these are not being included due to a bug in a regex on the client.

I have more details, and suggested fix in a PR here: https://github.com/phoenixframework/phoenix_live_view/pull/2332

Single File Example: https://gist.github.com/harmon25/966037dea4c3e5053ad2886ebeab17d5

### Expected behavior

Should be able to use `JS.navigate("/")` without resorting to `JS.navigate("/?")`  or `JS.navigate("/#")`

### PR DESCRIPTION
**Pull request by harmon25**
There seems to be a bug when navigating to the sites root via `JS.navigate/1`, and maybe other functions that use `LiveSocket.historyRedirect`

Can be reproduced by performing `JS.navigate("/")`  

The LV server process crashes with this CaseClauseError:

```
** (CaseClauseError) no case clause matching: %Phoenix.LiveView.Route{path: [], view: ComponentsWeb.HomeLive.Index, action: :index, opts: [action: :index, router: ComponentsWeb.Router], live_session: %{extra: %{on_mount: [%{function: &ComponentsWeb.InitAssigns.on_mount/4, id: {ComponentsWeb.InitAssigns, :default}, stage: :mount}], session: %{}}, name: :default, vsn: 1668894584134865752}, params: %{}, uri: %URI{scheme: nil, userinfo: nil, host: nil, port: nil, path: "/", query: nil, fragment: nil}}
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/channel.ex:990: Phoenix.LiveView.Channel.verified_mount/8
    (phoenix_live_view 0.18.3) lib/phoenix_live_view/channel.ex:59: Phoenix.LiveView.Channel.handle_info/2
```
My investigation has concluded it is because `scheme` and `host` are not being supplied with the `uri`, due to a regex in the JS code.

A workaround is to supply something innocuous to the URL like `/?`, which is `accepted` by the regex performed on the supplied href. 

I am not completely sure what the purpose of the regex is (what a surprise :P) ,  pretty sure it is only there to ensure this function is not called with an external URL. The proposed improvement solves the problem but is surely not as strict

There is probably a better way that does not involve a regex at all? 

fixes #2334

### CODE REVIEW

**Comment by harmon25** [comment]
Here is a [single file exs](https://gist.github.com/harmon25/966037dea4c3e5053ad2886ebeab17d5) that demonstrates the bug

File: assets/js/phoenix_live_view/live_socket.js [hunk 1]
```diff
@@ -739,7 +739,7 @@ export default class LiveSocket {
   historyRedirect(href, linkState, flash){
     // convert to full href if only path prefix
     if(!this.isConnected()){ return Browser.redirect(href, flash) }
-    if(/^\/[^\/]+.*$/.test(href)){
+    if(/^\/+.*$/.test(href)){
```
Comment (chrismccord) [inline assets/js/phoenix_live_view/live_socket.js:742]:
```suggestion
    if(/^\/$|^\/[^\/]+.*$/.test(href)){
```

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥
