### PR TITLE
Fix static_path in open_browser

### LINKED ISSUE #1295: open_browser doesn't display static paths when they are prefixed
I hit a bug with our implementation of https://github.com/phoenixframework/phoenix_live_view/pull/1280

My endpoint in config.exs is configured with: `static_url: [path: "/static"]`

When I use `open_browser` in tests, it gives me this for my app.css: `file:///path/to/my/static/static/css/app.css` whereas I expect `file:///path/to/my/static/css/app.css`.

I ended up updating my test endpoint config to have `static_url: [path: "/"]` to work around this.

Am I right that `prefix_static_path` should delete the path you configured in your endpoint when building the static path? cc @mcrumm @leandrocp

### PR DESCRIPTION
**Pull request by leandrocp**
Close #1295 - assume the default priv/static if static_url path is empty, otherwise resolve relative to priv dir, in other words:

`static_url: [path: "/static"]` will gerenate:

```
prefix: "/project/_build/test/lib/pulse/priv"
path: "/static/css/app.css"
```

And an empty `static_url` or empty static_url `path` will generate:

```
prefix: "/project/_build/test/lib/pulse/priv/static"
path: "/css/app.css"
```

/cc @mveytsman @mcrumm

### CODE REVIEW

File: lib/phoenix_live_view/test/client_proxy.ex [hunk 1]
```diff
@@ -87,9 +87,17 @@ defmodule Phoenix.LiveViewTest.ClientProxy do
...
+    static_url = endpoint.config(:static_url) || []
+
     static_path =
-      endpoint.config(:otp_app)
-      |> Application.app_dir("priv/static")
+      case Keyword.get(static_url, :path) do
+        nil ->
+          Path.join(priv_dir, "static")
+
+        path ->
```
Comment (josevalim) [inline lib/phoenix_live_view/test/client_proxy.ex:98]:
```suggestion
        _path ->
```

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
