### PR TITLE
Get the upload component id from the form's phx-target

### LINKED ISSUE #1357: Cannot test live file input in live component
### Environment

* Elixir version (elixir -v): 1.11.3-otp-23
* Phoenix version (mix deps): 1.5.4
* Phoenix LiveView version (mix deps): 0.15.1
* NodeJS version (node -v): 14.15.4
* NPM version (npm -v): 7.5.6
* Operating system: macOS
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

I have a `live_file_input` inside a live component in which I also call `allow_upload` inside the `mount` function. Uploading files works perfectly in dev, however when I run the test below, I get an error that says that uploads are not allowed for photo. 

An example can be found here: https://github.com/philippeqd/test-live-input-bug

I found that the error is raised  because I surrounded my `<form>` with a `<div>`. When I remove the `<div>`, then the tests pass. I cannot figure out why this happens and I am wondering whether it has to do with my selector in the `file_input`. 

**Test:**
```
test "upload", %{conn: conn} do
    {:ok, view, _html} = live(conn, "/")

    assert file_input(view, "#logo-upload", :photo, [
             %{
               name: "test.jpg",
               content: File.read!("test/static/images/test.jpg"),
               type: "image/jpeg"
             }
           ])
           |> render_upload("test.jpg") =~
             "<progress max=\"100\" value=\"100\""
  end
```

**Failing example**
```
<div>
  <form id="logo-upload" phx-submit="save" phx-change="validate" phx-target="<%= @myself %>">
    <%= live_file_input @uploads.photo %>
    <button type="submit">Upload</button>
    <%= for entry <- @uploads.photo.entries do %>
      <progress max="100" value="<%= entry.progress %>" class="h-1 w-40"/>
    <% end %>
  </form>
</div>
```

**Output:**
`  ** (RuntimeError) no uploads allowed for photo`

However, when I remove the surrounding `<div>`, then the test passes. 

**Working example**
```
<form id="logo-upload" phx-submit="save" phx-change="validate" phx-target="<%= @myself %>">
  <%= live_file_input @uploads.photo %>
  <button type="submit">Upload</button>
  <%= for entry <- @uploads.photo.entries do %>
    <progress max="100" value="<%= entry.progress %>" class="h-1 w-40"/>
  <% end %>
</form>
```

### Expected behavior
As the file uploading in my live component works perfectly in Dev mode, I expected that uploading files would work in the tests as well. With or without the surrounding `<div>`.

### PR DESCRIPTION
**Pull request by mcrumm**
Updates the component selector in [`file_input/4`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#file_input/4) to use the `phx-target` from the form input.

This could use a more robust set of tests around targeting.
Unless someone else beats me to it I will write them eventually :)

Closes #1357

### CODE REVIEW

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥 😍😍😍

File: lib/phoenix_live_view/test/client_proxy.ex [hunk 1]
```diff
@@ -778,11 +778,11 @@ defmodule Phoenix.LiveViewTest.ClientProxy do
     {:ok, root}
   end
 
-  defp maybe_cid(_tree, nil) do
+  def __maybe_cid__(_tree, nil) do
```
Comment (gcauchon) [inline lib/phoenix_live_view/test/client_proxy.ex:781]: What is the rational behind enclosing the function name with `__`, there are no other function in the module using this naming convention?

**Comment by philippeqd** [comment]
Thank you @mcrumm, I tested your PR locally and I can confirm that this solved #1357!

File: lib/phoenix_live_view/test/client_proxy.ex (hunk 1 above)
Comment (dvic) [reply lib/phoenix_live_view/test/client_proxy.ex:781]: Correct me if I'm wrong but I think it signals like "even though this is a public function, consider it private". In this case it's being called from `live_view_test.ex`.
