### PR TITLE
Fix issue with sticky remove transitions on push_navigate

### LINKED ISSUE #2756: `phx-remove` called in sticky live view
### Environment

* Elixir version (elixir -v): 1.14
* Phoenix version (mix deps): 1.7.3
* Phoenix LiveView version (mix deps): 0.19.1
* Operating system: Linux
* Browsers you attempted to reproduce this bug on (the more the merrier):  Firefox/Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

I have a LiveView page and within the `app.html.heex` layout, I render another sticky LiveView. This sticky LiveView is used to render notifications (as a fallback to native). Each rendered notification itself has a `phx-remove` to animate ("swipe away") when a button is clicked. When I push_navigate the page, the `phx-remove` animation is triggered and the notification is hidden (this animation also blocks the page transition until done). The element is not actually removed, and `render/1` is also never called.

```
phx-remove={JS.hide(transition: {"transition-all ease-linear", "opacity-0 translate-x-0", "opacity-100 translate-x-full"})}
```

### Expected behavior

Navigation should not trigger `phx-remove` inside sticky live views (as they aren't actually removed).

### PR DESCRIPTION
**Pull request by ismaelga**
Fixes #2756

@chrismccord Grabbed this one for me as it seemed very simple to fix

Let me know what you think. Glad to iterate towards a better patch
I don't like passing null to `this.transitionRemoves` but it should be ok.

### CODE REVIEW

File: assets/js/phoenix_live_view/live_socket.js [hunk 1]
```diff
@@ -400,7 +400,7 @@ export default class LiveSocket {
 
     this.main = this.newRootView(newMainEl, flash, liveReferer)
     this.main.setRedirect(href)
-    this.transitionRemoves()
+    this.transitionRemoves(null, true)
```
Comment (adamwight) [inline assets/js/phoenix_live_view/live_socket.js:403]: Any chance we can make this the default behavior? eg. reversing the parameter sense: `includingStickies[=false]`

Comment (adamwight) [inline assets/js/phoenix_live_view/live_socket.js:403]: If you flip the sense of the new parameter to `includingStickies[=false]`, then this invocation can still have empty parameters and the other usage in dom_patch will have two non-default parameter values.

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥
