### PR TITLE
Fix phx-static not being sent for child views

### LINKED ISSUE #974: Clarification about "assign_new" and its ability to access the assigns of the parent LV
### Environment

* Elixir version (elixir -v): Elixir 1.10.3 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps): 1.5.3
* Phoenix LiveView version (mix deps): 0.13.3
* NodeJS version (node -v): v13.13
* NPM version (npm -v): 6.14.4
* Operating system: NixOS GNU/Linux
* Browsers you attempted to reproduce this bug on (the more the merrier): FF, Chromium
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: yes

### Actual behavior

When  using `assign_new` to access the parent LV assigns, the lookup always fails. 

### Expected behavior
From what I understand from the [LiveView docs for `assign_new`](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#assign_new/3-referencing-parent-assigns) it is able to access the parent LV assigns when used on `mount`. From the docs:
```
[...]
Likewise, nested LiveView children have access to their parent's assigns on 
mount using assign_new, which allows assigns to be shared down the nested 
LiveView tree.
[...]
```
 From my tests this never works, I've also prepared a small test application [here](https://github.com/azazel75/nested_lv_assigns_test) where you can see that the root web page shows "value not found via 'assign_new'"  as the value of the `value` assign, that the child LV initializes in `mount`.

Now, I don't know if this is a real bug, if it's a problem with the phrasing in the docs or if it's a complete misunderstanding from me.  I thought also that passing down the assigns using the session map not the right thing to do, as it seems there to pass more "global" data and also it has a restriction on the keys that must be strings.

I've also asked on the forum here: https://elixirforum.com/t/nested-liveview-clarification-about-assign-new/32275 two days ago but there is no answer yet.

Please take five minutes to clarify what's the way to pass data to a child LV. 

Thanks

### PR DESCRIPTION
**Pull request by josevalim**
Closes #974.

### CODE REVIEW

**Comment by josevalim** [comment]
Unfortunately this is a bit more complex than I expected and it requires some code comments to explain some of the decisions. That's why it is in draft.

File: assets/js/phoenix_live_view.js [hunk 1]
```diff
@@ -1624,11 +1624,23 @@ export class View {
...
 
-    let newChildren = DOM.findPhxChildrenInFragment(html, this.id).filter(c => this.joinChild(c))
+    // One downside of this approach is that we need to find phxChildren
+    // in the html fragment, instead of directly on the DOM. The fragment
+    // also does not incldue PHX_STATIC, so we need to copy it over from
+    // the DOM.
+    let newChildren = DOM.findPhxChildrenInFragment(html, this.id).filter(toEl => {
+      let fromEl = toEl.id && this.el.querySelector(`#${toEl.id}`)
+      let phxStatic = fromEl && fromEl.getAttribute(PHX_STATIC)
+      if(phxStatic) toEl.setAttribute(PHX_STATIC, phxStatic)
```
Comment (chrismccord) [inline assets/js/phoenix_live_view.js:1640]:
```suggestion
      if(phxStatic){ toEl.setAttribute(PHX_STATIC, phxStatic) }
```

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥
