### PR TITLE
Provide escape hatch for connected mount errors. Closes #3379, #3454

### LINKED ISSUE #3379: LiveView causes infinite reload loop in browser when an Ecto error is raised in connected handle_params
### Environment

* Elixir version (elixir -v): 1.16.3
* Phoenix version (mix deps): 1.7.14
* Phoenix LiveView version (mix deps): 0.20.17
* Operating system: macOS 14.5
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes (no node_modules installed)

### Actual behavior

When an Ecto exception is raised within a `connected?(socket)` block in `handle_params`, LiveView goes into an infinite loop of full page browser reloads. The exception is not logged at all, and the reload loop is constant, not using any sort of backoff or retries, the entire browser page reloads over and over in an endless loop, with no logs.

This seems to happen specifically on Ecto errors, I assume due to how Ecto errors may be handled within Phoenix and LiveView?

This is a reproduction using PhoenixPlayground, you can change the different modules to see different behaviors.

```elixir
Mix.install([
  {:ecto_psql_extras, "~> 0.6"},
  {:ecto_sql, "~> 3.10"},
  {:phoenix_ecto, "~> 4.4"},
  {:phoenix_playground, "~> 0.1.0"}
], force: true)

defmodule Example do
  use Ecto.Schema

  @derive Jason.Encoder
  @primary_key {:id, Ecto.UUID, autogenerate: false}
  schema "example" do
    timestamps()
  end
end

# The InfiniteReloadLoop module will cause the browser to go into an uncontrollable
# loop of reloads, all while hiding logs of the actual exception. Nowhere in the logs
# does the exception appear, however the browser gets stuck in a page reload loop.
defmodule InfiniteReloadLoop do
  use Phoenix.LiveView

  def mount(_params, _session, socket) do
    {:ok, assign(socket, count: 0)}
  end

  def handle_params(_params, _uri, socket) do
    if connected?(socket) do
      raise Ecto.NoResultsError, queryable: Example
    end
    {:noreply, socket}
  end

  def render(assigns) do
    ~H"""
    """
  end
end

# The NotFoundErrorShown module will show Phoenix Ecto's error page for the "Not Found" exception.
# The exception will be logged in the apps logs as a debug log.
defmodule NotFoundErrorShown do
  use Phoenix.LiveView

  def mount(_params, _session, socket) do
    {:ok, assign(socket, count: 0)}
  end

  def handle_params(_params, _uri, socket) do
    raise Ecto.NoResultsError, queryable: Example
    {:noreply, socket}
  end

  def render(assigns) do
    ~H"""
    """
  end
end

# The NormalExceptionShowsCrash module will show the first render (from the initial dead view call),
# and then subsequently show a crash in the logs. It will periodically try to reconnect, and each time
# the crash in the logs will be shown.
defmodule NormalExceptionShowsCrash do
  use Phoenix.LiveView

  def mount(_params, _session, socket) do
    {:ok, assign(socket, count: 0)}
  end

  def handle_params(_params, _uri, socket) do
    if connected?(socket) do
      raise "Whoops"
    end
    {:noreply, socket}
  end

  def render(assigns) do
    ~H"""
    """
  end
end

# Set PhoenixPlayground to start a specific LV module based on which behavior you want to check.
PhoenixPlayground.start(live: InfiniteReloadLoop)
# PhoenixPlayground.start(live: NotFoundErrorShown)
# PhoenixPlayground.start(live: NormalExceptionShowsCrash)
```

### Expected behavior

Other exception types don't cause this infinite full page reload loop (as can be seen if you try using the `NormalExceptionShowsCrash` module in the playground script above), they instead seem to retry mounting on a retry with some sort of timer (console logs show an error that the join failed and eventually there is a retry). Additionally, app logs show the crash and error reason.

I would expect all exceptions to behave similarly, no full page reloads in an infinite loop, and crash logs being shown so that we can know why the app is in an infinite reload loop.

### PR DESCRIPTION
**Pull request by chrismccord**
Closes #3379, #3454

### CODE REVIEW

**Review by SteffenDE — APPROVED** [review]
Passing the token as cookie, clever solution, lgtm!

File: assets/js/phoenix_live_view/view.js [hunk 1]
```diff
@@ -809,8 +810,10 @@ export default class View {
 
   onJoinError(resp){
     if(resp.reason === "reload"){
-      this.log("error", () => [`failed mount with ${resp.status}. Falling back to page request`, resp])
-      if(this.isMain()){ this.onRedirect({to: this.href}) }
+      if(this.isMain()){
+        this.log("error", () => [`failed mount with ${resp.status} ${resp.token}. Falling back to page reload`, resp])
```
Comment (chrismccord) [inline assets/js/phoenix_live_view/view.js:814]:
```suggestion
        this.log("error", () => [`failed mount with ${resp.status}. Falling back to page reload`, resp])
```

File: lib/phoenix_live_view/static.ex [hunk 2]
```diff
@@ -82,6 +87,41 @@ defmodule Phoenix.LiveView.Static do
...
+            {:ok, %{status: status, exception: exception, stack: stack}}
+            when is_integer(status) ->
+              {status, exception, stack}
+
+            {:error, _reason} ->
+              {500, nil, []}
+          end
+
+        message = """
+        #{inspect(view)} raised #{exception} during connected mount sending a #{status} response.
```
Comment (josevalim) [inline lib/phoenix_live_view/static.ex:110]:
```suggestion
        #{inspect(view)} raised #{inspect(exception)} during connected mount sending a #{status} response
```

**Review by josevalim — APPROVED** [review]
