### PR TITLE
Sanitize phx-change attribute in formsForRecovery (#2252)

### LINKED ISSUE #2252: Invalid querySelector during reconnect
### Environment

* Elixir version (elixir -v): 1.13.4
* Phoenix version (mix deps): 1.6.12
* Phoenix LiveView version (mix deps): 0.17.11
* Operating system: MacOS
* Browsers you attempted to reproduce this bug on (the more the merrier):  Chrome, Safari
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior
the .js method `formsForRecovery(html)`  tries to select existing form elements to recover them after a disconnect.  

`let newForm = template.content.querySelector(`form[id="${form.id}"][${phxChange}="${form.getAttribute(phxChange)}"]`)`

this results in something like: `document.querySelector('form[id="myformID"][phx-change="[["push",{"event":"update","target":1}]]"]');`  which is an invalid selector.  The special characters need escaping.  This works... 
`document.querySelector('form[id="myformID"][phx-change="\\[\\[\\"push\\"\\,\\{\\"event\\"\\:\\"update\\"\\,\\"target\\"\\:1\\}\\]\\]"]');`

Of note, I have several forms on the page - not sure if a single form would suffer from this but I think so?

### Expected behavior
When there is a connection issue, I would expect to see the WebSocket errors, but not the querySelector problem. 

I think this would work (it's quieting errors for me, at least):
`let newForm = template.content.querySelector(`form[id="${form.id}"][${phxChange}="${CSS.escape(form.getAttribute(phxChange))}"]`)`

### PR DESCRIPTION
**Pull request by begedin**
When using the `JS` module to set `phx-change`, the call to `formsForRecovery` on frontend will fail due to not passing the attribute value correctly into a css selector.

Escaping is necessary for the css selector to become valid.

`CSS.escape` would be a more foolproof approach but jest does not support it in node env in which it runs. Not sure if it supports it in jsdom.

In that case, our best bet would be to stub `CSS.escape` and spy on it.

If that is the preferred approach here, I would be happy to do it some time tomorrow.

Resolves #2252

### CODE REVIEW

File: assets/js/phoenix_live_view/view.js [hunk 1]
```diff
@@ -1092,7 +1092,10 @@ export default class View {
         .filter(form => form.elements.length > 0)
         .filter(form => form.getAttribute(this.binding(PHX_AUTO_RECOVER)) !== "ignore")
         .map(form => {
-          let newForm = template.content.querySelector(`form[id="${form.id}"][${phxChange}="${form.getAttribute(phxChange)}"]`)
+          // attribute given via JS module needs to be escaped as it contains the symbols []",
+          // which result in an invalid css selector otherwise.
+          const phxChangeValue = form.getAttribute(phxChange).replaceAll(/([\[\]"])/g, '\\$1')
```
Comment (begedin) [inline assets/js/phoenix_live_view/view.js:1097]: Again, I could use `CSS.escape` here instead. 

https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape

But, it's not supported in the node env, so we would have to stub and spy on it, and not actually have a full input-output test.

File: assets/test/view_test.js [hunk 2]
```diff
@@ -225,6 +225,13 @@ describe("View + DOM", function(){
     view = new View(liveViewDOM(html), liveSocket)
     view.joinCount = 2
     expect(view.formsForRecovery().length).toBe(0)
+
+    html = "<form id='my-form' phx-change='[[\"push\",{\"event\":\"update\",\"target\":1}]]'><input name=\"foo\" /></form>"
+    view = new View(liveViewDOM(html), liveSocket)
+    view.joinCount = 1
+    const newForms = view.formsForRecovery(html)
+    expect(newForms.length).toBe(1)
+    expect(newForms[0][0].getAttribute('phx-change')).toBe('[[\"push\",{\"event\":\"update\",\"target\":1}]]')
```
Comment (begedin) [inline assets/test/view_test.js:234]: The test for the CSS.escape approach would need something like

Something like

```js
global.CSS = {
  escape: jest.spy().mockImplementation(v => v.replaceAll(/([\[\]"])/g, '\\$1'))
}
```
 before line 229

then 

```js
delete global CSS 
```

after line 234

**Comment by begedin** [comment]
Been thinking on this a bit more. Should escaping be happening in elixir, perhaps?

**Comment by begedin** [comment]
Anything I need to do to move this forward?

**Comment by chrismccord** [comment]
❤️❤️❤️🐥🔥
