### PR TITLE
Handle tag_close inside named slots

### LINKED ISSUE #1892: Improve error message on invalid conditional component slots
### Environment

* Elixir version (elixir -v): 1.13.2
* Phoenix version (mix deps): 1.6.6
* Phoenix LiveView version (mix deps): 0.17.7
* Operating system: macOS Monterey (12.1)
* Browsers you attempted to reproduce this bug on (the more the merrier): Chrome
* Does the problem persist after removing "assets/node_modules" and trying again? Yes/no: Yes

### Actual behavior

Error when using conditional slots:

**no case clause matching: %{file: "lib/phx_conditional_slots_example_web/templates/page/index.html.heex", root: nil, slots: [], stack: [substate: %{counter: {:atomics, #Reference<0.3277811488.2529034248.20745>}, dynamic: [], static: []}], subengine: Phoenix.LiveView.Engine, substate: %{counter: {:atomics, #Reference<0.3277811488.2529034248.20745>}, dynamic: [], static: ["\n "]}, tags: [{:tag_open, ":col", [{"let", {:expr, "user", %{column: 16, line: 3}}}, {"label", {:string, "Address", %{delimiter: 34}}}], %{column: 5, line: 3}}]}**

```
def table(assigns) do
    ~H"""
    <div class="table-responsive">
      <table class="table table-sm table-hover">
        <thead>
          <tr>
            <%= for col <- @col do %>
              <th><%= col.label %></th>
            <% end %>
          </tr>
        </thead>
        <tbody>
          <%= for row <- @rows do %>
            <tr>
              <%= for col <- @col do %>
                <td class={col[:class]}><%= render_slot(col, row) %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    """
  end
```

```
<PhxConditionalSlotsExample.Components.table rows={[%{name: "John", address: "Somewhere"}, %{name: "Jane", address: "Some place"}]}>
  <%= if true do %>
    <:col let={user} label="Address">
      <p><%= user.address %></p>
    </:col>
  <% end %>
</PhxConditionalSlotsExample.Components.table>
```

### Expected behavior

Error message

**invalid slot entry <:col>. A slot entry must be a direct child of a component**

If I remove the tag `<p>`, the error message changes to the `invalid slot`.

### PR DESCRIPTION
**Pull request by leandrocp**
Fix #1892

A template like

```elixir
<.function_component_with_single_slot>
<%= if true do %>
 <:sample>
   <p>inner</p>
 </:sample>
<% end %>
</.function_component_with_single_slot>
```

is tokenized as

```elixir
tokens: [
  {:tag_open, ":sample", [], %{column: 2, line: 3}},
  {:text, "\n   ", %{column_end: 4, line_end: 4}},
  {:tag_open, "p", [], %{column: 4, line: 4}},
  {:text, "inner", %{column_end: 16, line_end: 4}},
  {:tag_close, "p", %{column: 16, line: 4}},
  {:text, "\n ", %{column_end: 2, line_end: 5}},
  {:tag_close, ":sample", %{column: 2, line: 5}}
]
```

The `no case clause matching` happens due to the parsing of `{:tag_close, "p", %{column: 16, line: 4}}` which tries to set an unexpected root. So seems like the fix is to check if that tag is inside a named slot and no slots have been parsed yet (because slots are added only on `{:tag_close, ":sample", %{column: 2, line: 5}}`) if so then just skip (return current state) and keep evaluating the tokens, which eventually will raise the expected `ParserError`

### CODE REVIEW

**Comment by josevalim** [comment]
I think I have an idea. What if we initialize the state to `root: false` for nested nodes? I believe this would be inside the `token_state` call in `handle_end`. And we default it to nil in `handle_body`.

**Comment by leandrocp** [comment]
Tests are green locally on Elixir 1.13.0 / OTP24 so I'm gonna test on Elixir < 1.13

File: lib/phoenix_live_view/html_engine.ex [hunk 1]
```diff
@@ -82,21 +82,22 @@ defmodule Phoenix.LiveView.HTMLEngine do
   @doc false
   def handle_end(state) do
     state
+    |> Map.put(:root, false)
```
Comment (josevalim) [inline lib/phoenix_live_view/html_engine.ex:85]: Please pass it as non-optional parameter on token_state instead? :)

Comment (leandrocp) [reply lib/phoenix_live_view/html_engine.ex]: Sure!

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:
