### PR TITLE
Fix checkboxes and select on updates.

### LINKED ISSUE #615: Checkboxes check state can't be overwritten by server reliably
### Environment

* Elixir version (elixir -v):
Erlang/OTP 22 [erts-10.6.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.0 (compiled with Erlang/OTP 22)
* Phoenix version (mix deps):
phoenix branch 1.4
* Phoenix LiveView version (mix deps):
0e91c2576255124c912c7cdc5f94d2fae871d5ad (master HEAD)
* Operating system:
OS X

### Actual behavior
See: https://github.com/benwilson512/bug_example/blob/master/lib/demo_web/bad.ex

On page load there are two checkboxes, one checked, one unchecked. Clicking the submit button inverts the checked state of each. If you click on a check box, that checkbox is no longer affected by clicking the submit button, but the other is. Whichever is clicked last is unable to pick up changes.

It feels like a focus issue based on that description, but adding a text field or some other input to capture focus doesn't change anything. Perhaps related to https://github.com/phoenixframework/phoenix_live_view/issues/611 ?

### Expected behavior

I should be able to override the checked state.

### PR DESCRIPTION
**Pull request by chrismccord**
Sync checkbox checked props with server attr on updates.
Skip focused select attribute merge because FF has
quirky UI behavior when any setAttribute is called
on the select while in a hover state. Closes #615

// @snewcomer

### CODE REVIEW

File: assets/js/phoenix_live_view.js [hunk 1]
```diff
@@ -968,6 +970,12 @@ export let DOM = {
 
   isFormInput(el){ return /^(?:input|select|textarea|button)$/i.test(el.tagName) },
 
+  syncAttrsToProps(el){
+    if(el instanceof HTMLInputElement && el.type.toLocaleLowerCase() === "checkbox"){
```
Comment (mcrumm) [inline assets/js/phoenix_live_view.js]: So radio buttons also have a `.checked` property. Maybe we need:

`const CHECKABLE_INPUTS = ["checkbox", "radio"]`

```suggestion
    if(el instanceof HTMLInputElement && CHECKABLE_INPUTS.indexcOf(el.type.toLocaleLowerCase()) >= 0){
```

File: assets/js/phoenix_live_view.js [hunk 2]
```diff
@@ -968,6 +971,12 @@ export let DOM = {
 
   isFormInput(el){ return /^(?:input|select|textarea|button)$/i.test(el.tagName) },
 
+  syncAttrsToProps(el){
+    if(el instanceof HTMLInputElement && CHECKABLE_INPUTS.indexOf(el.type.toLocaleLowerCase()) >= 0){
+      el.checked = el.getAttribute("checked") !== null
+    }
+  },
```
Comment (snewcomer) [inline assets/js/phoenix_live_view.js]: As noted for future readers, this would require `<input type="checkbox" <%= @checked && "checked" %> />` and not work for `<input type="checkbox" />`.

File: assets/js/phoenix_live_view.js [hunk 3]
```diff
@@ -1055,10 +1064,12 @@ class DOMPatch {
 
         if(fromEl.isSameNode(focused) && DOM.isFormInput(fromEl)){
           this.trackBefore("updated", fromEl, toEl)
-          DOM.mergeInputs(fromEl, toEl)
+          DOM.mergeFocusedInput(fromEl, toEl)
+          DOM.syncAttrsToProps(fromEl)
```
Comment (snewcomer) [inline assets/js/phoenix_live_view.js]: Another way to think about this is `syncPropToAttr`.  If `fromNode.checked` (but no attribute), then force it on the `toNode.checked`.  In morphdom, we will convert this to an attr later on in the morphing process.

I think this might get around the need for `<%= @checked && "checked" %>` and avoid updating the `.checked` property if we don't need to on the `fromEl`.

https://github.com/patrick-steele-idem/morphdom/pull/177

Comment (snewcomer) [reply assets/js/phoenix_live_view.js]: @chrismccord 

https://github.com/patrick-steele-idem/morphdom/pull/177/commits/36360a206a1f940b62e56fc29abc543b287e4c7d

I think this commit outlines what exactly will happen when the `toNode` as a string does not contain any information that it should be checked.  It forces the `fromNode` to turn off checked.
